### ISSUE TITLE
Alternate way of uploading images

### ISSUE THREAD

**Issue by YanWittmann** [Tezumie/Image-to-Pixel#1]
First off, thank you for creating this!

I have one small problem with the UI: It only allows uploading images via drag-and-drop, which I cannot do on mobile devices. It would be nice if clicking the drop target, a file picker could open and let me select a file.

No rush or anything, I know that most users will use this in their browser on a desktop device, but I thought I'd let you know, since I first visited this project from your Reddit post on my phone and was seemingly unable to test the application.

If I'm just missing something, feel free to point me into the right direction!

**Comment by Tezumie** [comment]
I will work on that, could also try to make the layout mobile friendly too. Thank you for the feedback!

**Comment by Tezumie** [comment]
I have added an upload image button to allow for mobile or desktop <3
